### ISSUE TITLE
Timezone is different than of OS

### ISSUE THREAD

**Issue by mozky** [unktir/js-object-clock#1] opened 2024-04-16 19:16 UTC
**Describe the bug**
Wallpaper is displaying a different timezone than the one set on Windows 11. 

**To Reproduce**
1. Just enable the background
2. Used timezone GMT-6 Mexico Central is not used by wallpaper

**Expected behavior**
Time displayed on the wallpaper should match the OS timezone and time.

**Screenshots**
Windows 11 configuration:
![image](https://github.com/unktir/js-object-clock/assets/10691704/a6c85fb4-76b6-4ebe-9653-96ce76cd005a)

Background:
![image](https://github.com/unktir/js-object-clock/assets/10691704/095b6ca3-e8d1-49cb-bc3d-627d7f5eff1f)

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro. Version 23H2
 - Browser N/A
 - Version Wallpaper Engine Build 2.4.82

**Comment by unktir** [comment] 2024-04-17 15:02
As I remember, when I, along with Cucarachita Cosmica, tried to figure out what the reason was, we came to the conclusion that it was about switching to daylight saving time (DST).

So to get timezone offset I use the `getTimezoneOffset()` method of [`Date`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date), then I define the offset sign and define the offset converted to a hours.

https://github.com/unktir/js-object-clock/blob/91039dd54703f87106563847524858636da08efb/scripts/scripts.js#L4-L6

To get timezone offset I use the `getHours()` method of [`Date`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date)

https://github.com/unktir/js-object-clock/blob/91039dd54703f87106563847524858636da08efb/scripts/scripts.js#L8

But I think that the time is incorrectly define when creating the object `time` of the [`Date`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date) class.

https://github.com/unktir/js-object-clock/blob/91039dd54703f87106563847524858636da08efb/scripts/scripts.js#L2

As you can see, I use the native JS method of extracting the local date. And while reading various resources, I came across this post of [this blog](https://www.toptal.com/software/definitive-guide-to-datetime-manipulation), where it says:

> Due to differences between browser implementations and incorrect handling of Daylight Savings Time (DST), depending on the Date object for mission-critical applications is not recommended and you should probably be using a DateTime library like [Luxon, date-fns, or dayjs](https://github.com/you-dont-need/You-Dont-Need-Momentjs/blob/master/README.md#brief-comparison). (Whatever you use, avoid the once-popular Moment.js—often simply called moment, as it appears in code—since it’s now deprecated.)

In this regard, one of the solutions may be the addition of the DateTime library [dayjs](https://github.com/iamkun/dayjs). But at the moment there is no time to do it.

Then I came across the following answers, which made it clear that the windows time zones do not correspond to the IANA time zones (which JS uses, if I understood correctly) and they have to be converted.

1. [JavaScript Time Zone Offset does not match Windows Offset](https://stackoverflow.com/a/29522931/22098032)
2. [Moment.js uses a different time zone than the one defined in the system](https://stackoverflow.com/a/55464990/22098032)

Therefore, to find out where something is going wrong, I first switched to the same time zone as yours. Next, I decided to test windows using the command in the terminal`timezone` (or `Get-TimeZone`).

![image](https://github.com/unktir/js-object-clock/assets/92855970/402cadf2-9e71-4b76-9d28-d422ac293241)

Looks fine, as it should be. Then I open the clock via the local server in VSCode, everything is fine, but for some reason it does not work as it should through the Wallpaper Engine.

![изображение_2024-04-17_072719758](https://github.com/unktir/js-object-clock/assets/92855970/6741e8b3-6e46-4f21-b565-f90cf98cb338)

Next, I went to scour the Wallpaper Engine discussions, and found the [developer's answer](https://steamcommunity.com/app/431960/discussions/1/2789318172115081480/) for **Jan 13, 2019**, that the reason may be in the Windows time zone settings.

> What happens if you enable the "Ajustar automaticamente para o horário de verao" option there? I think I faintly remember reading about Brazil changing something about time zones or daylight savings time recently which bugged out some computer systems. These wallpapers do use the system time but maybe their DST settings somehow mismatch with what is set in Windows.
>
> Try to enable DST via the setting above and then maybe re-sync the time through Windows. Make sure to restart Wallpaper Engine afterwards.

I would be glad if you would check this statement.

And, given all of the above, I can't confidently figure out what could be causing such an bug. But I think it's probably the Wallpaper Engine itself. 

So let's check if this is true or not. I found a function that checks DST. [How to check if DST (Daylight Saving Time) is in effect, and if so, the offset?](https://stackoverflow.com/a/11888430/22098032).

Added it above the function `updateClock()` and added a condition in this function for displaying a message in a document. Added a tag with the id **'test'** immediately after the body tag.

```JS
Date.prototype.stdTimezoneOffset = function () {
    var jan = new Date(this.getFullYear(), 0, 1);
    var jul = new Date(this.getFullYear(), 6, 1);
    return Math.max(jan.getTimezoneOffset(), jul.getTimezoneOffset());
}

Date.prototype.isDstObserved = function () {
    return this.getTimezoneOffset() < this.stdTimezoneOffset();
}

var today = new Date();

function updateClock(object, settings) {
    ...
    if (today.isDstObserved()) { 
        document.getElementById("test").innerHTML = "Daylight saving time!";
    }
}
```
```HTML
<body>
    <p id="test"></p>
    ...
</body>
```

And here is the result

![image](https://github.com/unktir/js-object-clock/assets/92855970/ea4d0050-9cd5-4541-b7be-ff53cbeeb2e3)

And as we can see, for some reason there is a DST. And as I said, it turned out to be the Wallpaper Engine
Although I admit that I could have made a mistake in my researching, so I would be glad of any help

**Comment by unktir** [comment] 2024-04-17 20:13
I searched for where the wallpaper engine gets data for time zones and here is the [developer's answer](https://steamcommunity.com/app/431960/discussions/2/2944746708997035774) for **8 Sep, 2020** in the discussions.

> All clock systems are based on things provided by Google (Google Chrome and Google V8). Have your daylight saving times changed recently? Or has it been exactly like this since at least ~2 years?
>
> When governments change daylight saving times then it's required for Google to fix this and for Wallpaper Engine to receive the fixes first.

I also found possible ways to solve the problem from the [developer](https://steamcommunity.com/app/431960/discussions/2/2965020518372707810) for **1 Dec, 2020** without using additional libraries.

> You could also make a combo property and just let users manually select a timezone for example and then calculate the time offset manually. Kind of a hassle but that should be doable if you know some JavaScript (to calculate the offset time in SceneScript).

**Comment by mozky** [comment] 2024-04-23 01:53
Hi @unktir thanks for the exahustive research, it does make sense to me that this is caused by a DST mismatch, most of Mexico got rid of DST recently, and this is not the first time I've seen a bug of this type after such change.

If I open Control Panel settings, I can't see a DST setting for my Time zone, which is correct and expected.
![image](https://github.com/unktir/js-object-clock/assets/10691704/c690959e-e10a-48a3-86f8-0d2ed9e12503)
![image](https://github.com/unktir/js-object-clock/assets/10691704/ba6caf92-6b99-472b-8b4f-f7137b1d5cec)


So, according to this, I'm thinking I can maybe get around on this error on Chrome/V8 by simulating my timezone via switcing TZ to a one with DST, and manually disabling the DST setting; I did it and it works 🎉! changed my timezone to Central Time UTC-6 and disabled automatically adjust for DST.

Same hour as current Mexico time in Windows:
![image](https://github.com/unktir/js-object-clock/assets/10691704/e350af96-2287-4c90-8b5b-71f789ba9efa)

Wallpaper Engine displays the same hour since it handles this configuration as we want:
![image](https://github.com/unktir/js-object-clock/assets/10691704/e099b52f-1920-45f5-bf6a-ccb3101f93be)

**Comment by unktir** [comment] 2024-04-24 13:02
@mozky , have you tried to enable automatic time zone detection in windows settings?
I'm glad, of course, that you're happy with this solution to the issue. But in any case, I will try to solve the issue without transferring to another time zone  in windows settings as time comes.
I also opened a [discussion](https://steamcommunity.com/app/431960/discussions/1/4354493882933830033) in steam

**Comment by mozky** [comment] 2024-04-24 15:48
@unktir, yes, I usually have automatic time zone detection turned on which sets my TZ to Mexico as expected, sadly that's the TZ causing issues.

And of course, the solution I gave is not best since it will break at some point. Happy to help with resolving the issue.

**Comment by unktir** [comment] 2024-04-25 14:38
@mozky. The developer has responded to an open discussion and the [solution](https://steamcommunity.com/app/431960/discussions/1/4354493882933830033/#c4354493882934706766) will be either to switch to the beta, where this problem has already been fixed, or to wait for an update with this fix.

Here is the developer's response:
> Can you try the beta version? It should already be fixed there:
>
> https://steamcommunity.com/app/431960/discussions/1/1746720717352689476/

So you shouldn't change your time zone to another one but simply use your own or automatic one

**Comment by mozky** [comment] 2024-04-25 15:18
@unktir Tried with the beta version of wallpaper engine, and the issue seems to be solved 🎉 
![image](https://github.com/unktir/js-object-clock/assets/10691704/d79c1f1f-dbc0-4b4a-bc94-eb6a11860e33)
![image](https://github.com/unktir/js-object-clock/assets/10691704/0ae025cc-0475-4536-9ca4-dce2c8bcf13f)

**Comment by unktir** [comment] 2024-04-25 16:33
The developer's [response](https://steamcommunity.com/app/431960/discussions/1/4354493882933830033/?tscn=1714057627#c4354493882937886055) about the cause of this bug
> Mexico abandoned daylight savings time in 2023 and this was not updated into the part of the app that is responsible for web wallpapers yet.

**Closed as completed** 2024-04-25 16:33 UTC
Labels: bug, help wanted
